extinction:
  airmass: 'Kasten-Young'

noise:
  distribution: 'normal'
  parameters:
    sigma: 3
    mean: 10

catalogue: 'HYG30'

location:
  latitude: 48.15
  longitude: 17.06
  altitude: 185

pixels:
  x0: 800
  y0: 600
  xs: 0.0044
  ys: 0.0044

start:
  "2025-10-01T20:00:00"

projection:
  name: 'Borovička'
  parameters:
    x0: 0
    y0: 0
    a0: 1.570
    A: 0.0
    F: 0.0
    V: 0.5
    S: 0
    D: 0
    P: 0.00
    Q: 0.00
    epsilon: 0.0
    E: 0
