extinction:
  airmass: 'Kasten-Young'

catalogue: '../vasco/catalogues/HYG30.tsv'

location:
    latitude: 48.372763
    longitude: 17.373933
    altitude: 580

start: "2025-10-01T20:00:00"
count: 50

cores: 4

projection:
  name: 'Borovička'
  parameters:
    x0: 0
    y0: 0
    a0: 1.570
    A: 0.0
    F: 0.0
    V: 0.5
    S: 0
    D: 0
    P: 0.00
    Q: 0.00
    epsilon: 0.0
    E: 0
