extinction:
  airmass: 'Kasten-Young'

noise:
  distribution: 'normal'
  parameters:
    sigma: 3
    mean: 10

catalogue: 'HYG30'

location:
  latitude: 48.15
  longitude: 17.06
  altitude: 185

projection:
  name: 'Borovička'
  parameters:
    x0: 0
    y0: 0
    a0: 0
    A: 0.0
    F: 0.0
    V: 1
    S: 0
    D: 0
    P: 0.01
    Q: 0.01
    epsilon: 1.2
    E: 1.57
